import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-gray-800" lang="en">
      <SessionProvider>
        <body className={montserrat.className}>
          <Navbar />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
